config/routes.rb
Rails.application.routes.draw do
  root "top#index"
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  resources :users, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :error
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    @user = login(params[:email], params[:password]) 
    if @user
      redirect_to root_path, success: 'ログインできましたねえ'
    else
      flash.now[:error] = 'Login failed'
      @user = User.new(name: params[:name], email: params[:email], password: params[:password])
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'Logged out!', status: :see_other
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to root_path, success: 'Welcome to the site!'
    else
      flash.now[:error] = 'Login failed'
      render :new, status: :unprocessable_entity
    end
  end
  
private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="cupcake">
  <head>
    <title>Oasobi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex flex-col">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/top/index.html.erb
<div>
  <div class="font-bold">
    top#indexとはここじゃよ
  </div>

  <div class="flex">
   <% if logged_in? %>
     <p>ログイン中</p>
    <%= link_to "ログアウト", logout_path, method: :delete, data: { turbo_method: :delete }, class: 'btn' %>
   <% else %>
     <p>ログアウト中</p>
     <%= link_to "ログイン", login_path, class: 'btn' %>
     <%= link_to "新規登録", new_user_path, class: 'btn' %>
   <% end %>
  </div>
</div>

app/views/user_sessions/new.html.erb
<div>
 <h1>ログインページはここじゃよ</h1>
 <%= form_with model: @user, url: login_path, data: { turbo: false } do |f| %>
   <div> 
     <div> 
       <%= f.label :name %>
     </div>
     <div>
       <%= f.text_field :name %>
     </div>
   </div>

   <div>
     <div>
       <%= f.label :email %>
     </div>
     <div>
       <%= f.email_field :email %>
     </div>
   </div>

   <div>
     <div>
       <%= f.label :password %>
     </div>
     <div>
       <%= f.password_field :password %>
     </div>
   </div>

   <div>
     <%= f.submit 'ログイン', class: 'btn' %>
   </div>
 <% end %>
 <%= link_to '戻る', root_path, class: 'btn' %>
</div>

app/views/users/new.html.erb
<div>
  <h1 class="font-bold">Users#new</h1>
  <%= form_with model:@user do |f| %>
    <div>
      <div>
        <%= f.label :name %>
      </div>
      <div>
        <%= f.text_field :name %>
      </div>
      
      <div> 
      <%= f.label :email %>
      </div>
      <div>
      <%= f.email_field :email %>
      </div>

      <div>
      <%= f.label :password %>
      </div>
      <div>
      <%= f.password_field :password %>
      </div>

      <div>
      <%= f.label :password_confirmation %>
      </div>
      <div>
      <%= f.password_field :password_confirmation %>
      </div>

      <%= f.submit '登録', class: 'btn' %>
     </div>
  <% end %>
  <%= link_to '戻る', root_path, class: 'btn' %>
</div>